### ISSUE TITLE
mod_php not installed/enabled

### ISSUE THREAD

**Issue by rockholla** [geerlingguy/ansible-role-drupal#20]
So noticed this after a fresh provision using a playbook with this role on Ubuntu 14.04 (ubuntu/trusty64) via Vagrant.  Accessing the site on the VM rendered the index.php text, so went to check the Apache config on the VM to see if php mod was installed/enabled and noticed it wasn't.

It's quite possible I'm missing something here as I'm relatively new to Ansible, but seems like based on [your ansible php role notes](https://github.com/geerlingguy/ansible-role-php#role-variables), setting drupal-required php packages, including `libapache2-mod-php5`, should be done somewhere in this role.

Happy to contribute a PR if I'm on the right track.  Just let me know.

**Comment by geerlingguy** [comment]
Thanks for opening this issue! To be honest, I haven't updated this role with some of the latest changes I've been testing in Drupal VM, the Pi Dramble, and elsewhere, in a few months. I hope to get this role back into the best shape possible soon (maybe by DrupalCon!), including updating the docs.

My PHP role now defaults to setting up PHP-FPM, so with Apache, you can install mod_proxy_fcgi and set up a ProxyPassMatch directive to route requests to FPM; see this example: https://github.com/geerlingguy/drupal-vm/blob/master/example.config.yml#L83

Otherwise, yes, you will need to update the default `php_packages` list and add libapache2-mod-php5 (or install it separately in your playbook). Another option is to use Nginx, but that's not yet supported by this role (hopefully soon though!).

**Comment by geerlingguy** [comment]
Closing this out, as I'm working on completely rewriting the role for the next release, so it will work a lot more smoothly with multiple Drupal workflows (especially focused on Drupal 8, but also for D7 and somewhat D6). See: https://github.com/geerlingguy/ansible-role-drupal/issues/23
