### ISSUE TITLE
Site install only supports a local PostgreSQL database

### ISSUE THREAD

**Issue by yock** [geerlingguy/ansible-role-drupal#46]
https://github.com/geerlingguy/ansible-role-drupal/blob/master/tasks/install-site.yml#L11-L19

A remote instance would require a hostname and credentials to be passed to the `psql` command. The playbook currently `become`s the Postgres user, which seems ideal for local database servers. I can think of two possible ways to support both local and remote PostgreSQL servers, though there may be more.

* Check the value of `drupal_db_host` in the `when` test for `localhost` and/or `127.0.0.1`. Invert the test for a second task which uses passes host and credentials to `psql` and omits `become` and `become_user`.
* Pass credentials to `psql` for local instances.

**Comment by geerlingguy** [comment]
> Pass credentials to psql for local instances.

I'd rather not do that if possible, just because it can have some weird side-effects and also might break more frequently than using a become_user.

I would be okay with switching between two tasks, though—if Postgres is on a separate server, run a task that requires user/pass, but if it's on the same server, become the user.

We'd need to document this in the README of course. Good catch, though! So far, I haven't built any clusters with Postgres (only MySQL), that's why I haven't run into this bug myself yet.

**Comment by yock** [comment]
What do you think would be the definitive test for local vs remote? Is a check of the value set in `drupal_db_host` sufficient? Is there a more robust test? Or maybe a boolean that the user would set?

**Comment by geerlingguy** [comment]
@yock - If there's not something simple, I'd say maybe a boolean the user controls (the person using the role should know if they need to connect to a local instance or remote).

**Comment by jonathangreen** [comment]
+1 

Just wanted to chime in that I am also having this problem with remote psql instances. I think the the Boolean option probably makes sense to let the user choose what they want.
