### ISSUE TITLE
Run drush config-import, as part of a site update

### ISSUE THREAD

**Issue by bryanbraun** [geerlingguy/ansible-role-drupal#47]
Hey @geerlingguy 👋 

I'd like to be able to import configuration (via `drush config-import`) when using this role to deploy a site.

Ideally this would happen before `drush updatedb`, that way update hooks can build on top of the config changes. For example:

- config-import creates a role, and updb creates a user with that role. Or,
- config-import defines a content type, and updb creates a node of that content type.

It should be a quick addition to `update.yml`. I'm not sure if there are cases when somebody wouldn't want it, but if so, we could add a flag to enable/disable it.

I'm happy to put together a PR, if this is something you're interested in.

**Comment by geerlingguy** [comment]
@bryanbraun - I would rather support this via https://github.com/geerlingguy/ansible-role-drupal/issues/34 — it would allow some more generic 'do these things after a code update' support.

Since some people use config management, others features + custom modules, and others nothing at all (config is just managed on prod, how quaint!), it would be tricky to try to add support for one certain method over others.

Please take a look at that other issue and see if it would meet your needs. Thanks!
