### ISSUE TITLE
Moving the make file breaks includes[] or make_local relative paths.

### ISSUE THREAD

**Issue by mikecrittenden** [geerlingguy/ansible-role-drupal#55]
Is there any specific reason why the file needs to be moved to /tmp before running? In my testing that seems to break things like `includes[] = another-makefile.make` inside my make file, or anything local meant to be pulled in via https://github.com/helior/make_local

**Comment by oxyc** [comment]
The related issues:
- https://github.com/geerlingguy/drupal-vm/issues/84
- https://github.com/geerlingguy/drupal-vm/pull/412

**Comment by oxyc** [comment]
Main issue is that makefile can be in an arbitrary path, it doesn't have to be in the root of the project. When building on a remote server, we need to copy it into place and knowing the correct location when the path can be absolute on the host machine makes it very difficult.

**Comment by mikecrittenden** [comment]
@oxyc Ok - that makes sense I suppose. If that's the case, then is there any way to alter the build-makefile.yml tasks without just hacking that file, by maybe copying the file somewhere else or something?

**Comment by oxyc** [comment]
I guess you're not using composer at all? If you are there are some [uncommitted docs](https://github.com/geerlingguy/drupal-vm/pull/1256/commits/1c53c9b400b582b2ac38300c823128a2b04a6288) in an open PR on how to apply patches when Drupal VM is a composer dependency.

But maybe we could just use either a custom variable for where to move it rather than hardcoding `/tmp`. Or just use `{{ drupal_core_path }}` as that would be more intuitive.

**Comment by oxyc** [comment]
You can run `drush make` in an existing directory right? A while since I used it so can't remember...

**Comment by mikecrittenden** [comment]
Ah, I am installing DrupalVM via composer so yeah I can just patch it, no
problem. I just wasn't sure if there was a more official way of customizing
ansible tasks. And yeah, I believe drush make in an existing dir works
fine. Thanks for the help!

**Comment by oxyc** [comment]
Unfortunately in this case there's not. But it sounds like your use case should be supported. Lets see if @geerlingguy has any opinions :)

Maybe just moving the makefile to `{{ drupal_core_path }}/{{ drush_makefile_path|basename }}` instead? This could theoretically overwrite a file in odds edge cases (which is why I opted for `/tmp`):
- project.make.yml <- overwritten
- config/project.make.yml <- path where `drush_makefile_path` points

**Comment by mikecrittenden** [comment]
Just for the record, I threw up https://github.com/geerlingguy/ansible-role-drupal/pull/56 which just builds it where it already exists instead of moving it anywhere. That works for me in my particular situation, but obviously (as discussed above) doesn't work in general so it shouldn't be merged.

Feel free to close that PR immediately, but I thought it might be useful to have as a reference for anyone else who sees this.

**Comment by geerlingguy** [comment]
@mikecrittenden - To better support your use case, I'd be willing to merge what you did in #56 if you want to preserve the copy task, but add a new `when` conditional to it (https://github.com/geerlingguy/ansible-role-drupal/pull/56/files#diff-64c850ae80dcec6c362963ca4cba0a66L6) like:

```yaml
- name: Copy drush makefile into place.
  copy:
    src: "{{ drush_makefile_path }}"
    dest: /tmp/drupal.make.yml
  when:
    - not drupal_site_exists
    - drush_makefile_copy
```

Then we could maybe set the `Generate Drupal site with drush makefile.` task to use `drush_makefile_path` if `drush_makefile_copy` is true, or `/tmp/drupal.make.yml` if not...

**Comment by mikecrittenden** [comment]
Could you give me a pointer about how to do the last part (use `drush_makefile_path` or `/tmp/drupal.make.yml` depending on whether `drush_makefile_copy` is true)? Would that have to be two separate tasks with opposite `when`'s, or can that still be in the same task?
